hlxsites/theplayers

blocks/cards/cards.css, blocks/cards/cards.js
Allow champion cards to accept curated content.
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.live/past-champions
- After: https://champion-cards-curated--theplayers--hlxsites.hlx.live/past-champions
- After: https://champion-cards-curated--theplayers--hlxsites.hlx.page/drafts/fkakatie/sentry-past-champions
- After: https://champion-cards-curated--theplayers--hlxsites.hlx.page/drafts/fkakatie/wgc-past-champions
=> champion cards with curated content rather than from a feed

blocks/carousel/carousel.css, blocks/carousel/carousel.js
This was required for WGC Dell Match play site, since there is no stats feed for that course. So it's manually authored but has a slightly different set of elements.
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/course
- After: https://course-carousel-flexibility--theplayers--hlxsites.hlx.page/course
- After: https://course-carousel-flexibility--theplayers--hlxsites.hlx.page/drafts/shsteimer/wgc-dell-course
=> feat: provide flexibility in course carousel when not driven from the stats feed

blocks/field/field.js
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/field
- After: https://universal-field--theplayers--hlxsites.hlx.page/field
- After: https://universal-field--theplayers--hlxsites.hlx.page/
update field block to read placeholders to build request url (existing behavior always pulls the players)
=> fix: use placeholders in field block

blocks/header/header.css, blocks/header/header.js
better stying for proud partners, correct display for brand with section metadata
Test URLs:
- After: https://header-partners-fix--theplayers--hlxsites.hlx.page/
=> fix: proud partners styling with section metadata

blocks/tee-times/tee-times.js
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/tee-times
- After: https://tee-times-bug--theplayers--hlxsites.hlx.page/tee-times
- After: https://tee-times-bug--theplayers--hlxsites.hlx.page/
tee time of noon was being misread as 0:00am
=> fix: tee-times noon bug

blocks/images/images.css
support for Images (small) block variant (capping img widths at 330px)
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/wgc-sponsors
- After: https://small-images-variant--theplayers--hlxsites.hlx.page/drafts/fkakatie/wgc-sponsors
=> feat: support for small images variant

blocks/past-results/past-results.css, blocks/past-results/past-results.js
Test URLs:
- After: https://past-results-switch--theplayers--hlxsites.hlx.page/
~~missing switch in past results fetch causes buggy behavior, so if switch does not exist, we'll build it~~
Instead of adding a switch if there is none, I'm now just setting the default view and checking against that when sorting.
=> fix: if switch is missing, build in past results

blocks/news/news.js
checking for relative links now that some domains have moved from `pgatour.com`
Test URLs:
- After: https://news-relative-links--theplayers--hlxsites.hlx.page/
=> fix: check for relative links in news feed

blocks/promotion/promotion.js
presidents cup is more than a year away, which breaks the current rolex countdown config. apparently, the start and end dates don't matter (in that they can be a two-year, 20-year, 500-year gap), but 5 years seems reasonable.
Test URLs:
- After: https://promotion-rolex-fix--theplayers--hlxsites.hlx.page/
=> fix: rolex countdown should account for tournaments more than a year in the future

blocks/ads/ads.js
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/news/2022/10/21/nemours-childrens-health-jacksonville-2-million-gift
- After: https://ads--theplayers--hlxsites.hlx.page/news/2022/10/21/nemours-childrens-health-jacksonville-2-million-gift
=> fix: catch if bottom ad has been closed

blocks/carousel/carousel.css
Test URLs:
- After: https://course-credit-wrap--theplayers--hlxsites.hlx.page/
=> fix: stop course feed credits from wrapping on desktop

blocks/cards/cards.css, blocks/columns/columns.css
small fix for image aspect ratios on cards and columns...
https://main--theplayers--hlxsites.hlx.page/tickets
vs.
https://card-columns-images--theplayers--hlxsites.hlx.page/tickets
other pages:
https://card-columns-images--theplayers--hlxsites.hlx.page/past-champions
https://card-columns-images--theplayers--hlxsites.hlx.page/hospitality
=> chore: adjust images / columns

styles/styles.css
See #68 
This is a better fix. After merging, I realized that using `:first-of-type` caused the main copy font to be smaller when there was no `<p>` before the `<h2>`, so back to using `:first-child` but making is specific to `<p>`
See  https://main--theplayers--hlxsites.hlx.page/drafts/shsteimer/charity and https://teaser-h2-fontsize--theplayers--hlxsites.hlx.page/drafts/shsteimer/charity for an example of this.
This should solve for all scenarios.
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
- After: https://teaser-h2-fontsize--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
=> fix: a better way of preserving h2 style

blocks/player-feature/player-feature.js
After #65 happened to pull this up on my iPhone and noticed the video id was being transformed into a button in the button container (oddity with mobile safari turning the video id that looks like a phone number into a tel: link and then decorate buttons function merging it into the container since they are siblings). This fixes that by detecting the tel link and then killing off the element.
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/past-champions/archive/al-geiberger-1975
- After: https://mobile-safari-video-fix--theplayers--hlxsites.hlx.page/past-champions/archive/al-geiberger-1975
=> Mobile safari video fix

scripts/delayed.js, scripts/scripts.js
~~this will allow you to determine which percentage of visitors get the Adobe Launch script~~
The goal is to be able to track if Adobe Analytics is tracking the page view, so we intercept the creation of the `window.s` variable, and install a proxy that traps the `s.t()` function call. https://experienceleague.adobe.com/docs/analytics/implementation/js/overview.html?lang=en
- After: https://launch-rum--theplayers--hlxsites.hlx.page/?rum=on
=> feat(rum): track when and if Adobe Analytics tracking is executed

scripts/delayed.js, scripts/scripts.js
Test URLs:
- After: https://new-analytics--theplayers--hlxsites.hlx.page/
See slack thread at https://adobe-dx-support.slack.com/archives/C03GXBSC72T/p1677697088579909?thread_ts=1677505316.250869&cid=C03GXBSC72T for context.
I think there is a bunch of stuff in delayed related to login and favorite players that im not sure we use anywhere and could maybe just eliminate, but I wasn't 100% sure about all that so left it for now.
=> New analytics

blocks/news/news.js, blocks/related-stories/related-stories.js
adjustment for news articles now that feeds are live.
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/news/2023/03/06/driving-dialogue-for-mental-health
- After: https://news-fix--theplayers--hlxsites.hlx.page/
- After: https://news-fix--theplayers--hlxsites.hlx.page/news/2023/03/06/driving-dialogue-for-mental-health
=> fix: remove webview param from article links. use video shareUrl now that it works

blocks/footer/footer.js, blocks/header/header.js, blocks/sponsors/sponsors.js
https://partner-change--theplayers--hlxsites.hlx.page/sponsors
vs.
https://main--theplayers--hlxsites.hlx.page/sponsors
https://partner-change--theplayers--hlxsites.hlx.page/
vs.
https://main--theplayers--hlxsites.hlx.page/
=> chore: adding more selective partner logic

blocks/footer/footer.js, blocks/header/header.js
two reasons for this:
1 for sites with no sponsors nav, we won't set the value, saving on an http request that will 404
2. for pres cup, the sponsors page has no sponsors block, so need the nav content in a separate fragment
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/sponsors
- After: https://sponsors-ph--theplayers--hlxsites.hlx.page/
- After: https://sponsors-ph--theplayers--hlxsites.hlx.page/sponsors
=> chore: move path for sponsors nav content to a placeholder

scripts/delayed.js, scripts/scripts.js
ticket: https://pgatour.atlassian.net/browse/TDW-1646
Test URLs:
- After: https://feat-b-TDW-1646-Admiral--theplayers--hlxsites.hlx.page/
=> TDW-1646 Add Admiral Script
