hlxsites/theplayers

- blocks/ads/ads.css
- blocks/ads/ads.js
- blocks/ads/rolex/rolex.frameToggleMobile.html
- blocks/ads/rolex/toggle-mobile.min.js
- blocks/ads/rolex/toggle-mobile/img/hours.svg
- blocks/ads/rolex/toggle-mobile/img/minutes.svg
- blocks/ads/rolex/toggle-mobile/img/seconds.svg
- blocks/ads/rolex/toggle.min.js
- scripts/scripts.js
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/tee-times
- After: https://ads-test--theplayers--hlxsites.hlx.page/tee-times
> feat: multiple ads per page

- blocks/footer/footer.js
- blocks/header/header.css
- blocks/header/header.js
- blocks/news/news.js
- tools/importer/import.js
Basis for other projects that would require the minimum of changes (readme, fstab adn favicon)
> feat: more generic

- blocks/header/header.js
- scripts/delayed.js
Fix #<gh-issue-id>
Test URLs:
- After: https://header-gigya--theplayers--hlxsites.hlx.page/
> fix: dynamic module import

- blocks/carousel/carousel.css
- blocks/footer/footer.css
- blocks/header/header.css
- blocks/news/news.css
- blocks/past-results/past-results.css
- blocks/player-feature/player-feature.css
- blocks/social/social.css
Refactor blocks to use local color variables
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page
- After: https://color-variables--theplayers--hlxsites.hlx.live
> Color variables

- blocks/social/social.css
- blocks/social/social.js
Show more/less on the social block, needed for wgc dell match play site.
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/shsteimer/social
- After: https://block-social-collapsible--theplayers--hlxsites.hlx.page/drafts/shsteimer/social
- Collapsible: https://block-social-collapsible--theplayers--hlxsites.hlx.page/drafts/shsteimer/social-collapsible
> collapsible (show more/less) social block

- blocks/social/social.css
Fix #<gh-issue-id>
Test URLs:
- After: https://social-image-feed-fix--theplayers--hlxsites.hlx.page/
> fix: maintain aspect ratio on larger screens

- scripts/scripts.js
- styles/styles.css
Support for video teasers as needed for wgc dell site
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
- After: https://video-teasers--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
- After: https://video-teasers--theplayers--hlxsites.hlx.page/drafts/shsteimer/charity
> feature: videolink for teasers

- blocks/news/news.css
- blocks/news/news.js
Add feature to news block to allow curated/pinned items
Test URLs:
Before: https://main--theplayers--hlxsites.hlx.page/news
After: https://curated-news-items--theplayers--hlxsites.hlx.page/news
After: https://curated-news-items--theplayers--hlxsites.hlx.page/drafts/shsteimer/news-filtered
After: https://curated-news-items--theplayers--hlxsites.hlx.page/drafts/shsteimer/senty-toc-index-news
After: https://curated-news-items--theplayers--hlxsites.hlx.page/drafts/shsteimer/wgc-dell-index-news
> feature: curated/pinned news items

- blocks/leaderboard/leaderboard.css
- blocks/leaderboard/leaderboard.js
- scripts/delayed.js
- styles/lazy-styles.css
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/
- After: https://universal-leaderboard--theplayers--hlxsites.hlx.page/
- After: https://universal-leaderboard--theplayers--hlxsites.hlx.page/drafts/fkakatie/
> feat: universal leaderboard, favorite player func

- styles/styles.css
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
- After: https://fix-teaser-flex--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
> fix: add cls fix to media query selector so cascade is maintained

- blocks/blockquote/blockquote.css
- blocks/cards/cards.css
- blocks/carousel/carousel.css
- blocks/field/field.css
- blocks/hero/hero.css
- blocks/past-results/past-results.css
- blocks/related-stories/related-stories.css
- blocks/share/share.css
- blocks/sponsors/sponsors.css
- blocks/table/table.css
- blocks/tee-times/tee-times.css
Test URLs:
- After: https://block-variables--theplayers--hlxsites.hlx.page/
> feat: extend block scope variables

- blocks/table/table.css
- blocks/table/table.js
table can now consume stat feed
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/tour-index
- After: https://table-stats--theplayers--hlxsites.hlx.page/drafts/fkakatie/tour-index
> feat: table stats variant

- blocks/news/news.js
https://main--theplayers--hlxsites.hlx.live/
vs.
https://local-news--theplayers--hlxsites.hlx.live/
> feat: add tournament news

- blocks/embed/embed.css
- blocks/embed/embed.js
- blocks/weather/weather.css
embed block now supports spotify and facebook links
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/virtual-fan-zone
- After: https://embed-support--theplayers--hlxsites.hlx.page/drafts/fkakatie/virtual-fan-zone
> feat: add facebook, spotify to embed

- blocks/hero/hero.css
- blocks/hero/hero.js
- scripts/scripts.js
https://dynamic-fonts--theplayers--hlxsites.hlx.live/news/2022/10/11/pace-center-for-girls-grant-the-players-village
https://dynamic-fonts--theplayers--hlxsites.hlx.live/news/2022/08/17/the-players-championship-grant-funding-2022
vs.
https://main--theplayers--hlxsites.hlx.live/news/2022/10/11/pace-center-for-girls-grant-the-players-village
https://main--theplayers--hlxsites.hlx.live/news/2022/08/17/the-players-championship-grant-funding-2022
mobile breakpoint
> chore: add more flexible hero headline sizing

- blocks/carousel/carousel.css
- blocks/carousel/carousel.js
- blocks/hero/hero.css
- blocks/hero/hero.js
on desktop, read more buttons are separated from cta buttons
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/read-more
- After: https://read-more-btn--theplayers--hlxsites.hlx.page/drafts/fkakatie/read-more
> feat: alt read more button styling

- blocks/cards/cards.css
- blocks/cards/cards.js
- blocks/columns/columns.css
- blocks/columns/columns.js
cards and columns blocks support subtitle
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/subtitle-test
- After: https://card-column-subtitle--theplayers--hlxsites.hlx.page/drafts/fkakatie/subtitle-test
> feat: card and column support subtitle

- blocks/social/social.css
- blocks/social/social.js
- scripts/scripts.js
Added support for Facebook in social feed for CJ Cup.
See original at: https://www.pgatour.com/tournaments/the-cj-cup.html
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/social
- After: https://social-fb-support--theplayers--hlxsites.hlx.page/social
- CJ Cup FB Version: https://social-fb--pga-the-cj-cup--hlxsites.hlx.page/
> feat: fb feed for social widget

- scripts/delayed.js
https://main--theplayers--hlxsites.hlx.live/
vs.
https://onetrust-placeholder--theplayers--hlxsites.hlx.live/
> chore: make onetrust configurable

- scripts/delayed.js
https://main--theplayers--hlxsites.hlx.live/
vs.
https://ot-handling--theplayers--hlxsites.hlx.live/
> chore: better ot handling

- blocks/player-feature/player-feature.js
Player feature may not have links (see Presidents Cup).
Test URLs:
- After: https://player-feature-fix--theplayers--hlxsites.hlx.page/
> fix: player feature authoring is more forgiving

- blocks/columns/columns.css
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/columns
- After: https://columns-img-stretch--theplayers--hlxsites.hlx.page/drafts/fkakatie/columns
> fix: stretch column image to fit height

- blocks/carousel/carousel.css
- scripts/scripts.js
Partial fix https://github.com/hlxsites/pga-tour-issues/issues/25
Test URLs:
- After: https://carousel-btns--theplayers--hlxsites.hlx.page/
> fix: combining btn containers and carousel btn wrap

- blocks/hero/hero.css
Partial fix https://github.com/hlxsites/pga-tour-issues/issues/25
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/tickets
- After: https://hero-spacing--theplayers--hlxsites.hlx.page/tickets
> fix: center hero text

- blocks/cards/cards.css
- blocks/columns/columns.css
https://columns-font-size--theplayers--hlxsites.hlx.live/tickets
vs. 
https://main--theplayers--hlxsites.hlx.live/tickets
additional:
https://columns-font-size--theplayers--hlxsites.hlx.live/hospitality
https://columns-font-size--theplayers--hlxsites.hlx.live/
https://columns-font-size--theplayers--hlxsites.hlx.live/volunteer/
> chore: remove special font sizes in columns

- blocks/promotion/promotion.js
Test URLs:
- After: https://promotion-bug--theplayers--hlxsites.hlx.page/
> fix: execute get minutes function

- blocks/course/course.css
- blocks/course/course.js
rethinking the carousel (course/course feed) variant
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/fkakatie/course
- After: https://course-refactor--theplayers--hlxsites.hlx.page/drafts/fkakatie/course
> refactor: course block

- blocks/columns/columns.css
As required for https://main--pga-dominion-energy-charity-classic--hlxsites.hlx.live/charity
Test URLs:
Before: https://main--theplayers--hlxsites.hlx.page/
After: https://cols-small-imgs--theplayers--hlxsites.hlx.page/
Before: https://main--theplayers--hlxsites.hlx.page/drafts/shsteimer/domion-charity
After: https://cols-small-imgs--theplayers--hlxsites.hlx.page/drafts/shsteimer/domion-charity
> Cols small imgs

- blocks/embed/embed.js
- blocks/leaderboard/leaderboard.js
- scripts/delayed.js
- scripts/scripts.js
also refactored to a single loadScript function
Fix: https://github.com/hlxsites/pga-tour-issues/issues/28
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/shsteimer/tickets
- After: https://livechat-autoblock--theplayers--hlxsites.hlx.page/drafts/shsteimer/tickets
> feature: loading live chat in delayed 

- blocks/video/video.js
Update video player id + some optimizations to lazy load videos until we need them
New player ID based on https://adobe-dx-support.slack.com/archives/C03GXBSC72T/p1667413712026009
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/past-champions/archive/al-geiberger-1975
- After: https://updated-video-player--theplayers--hlxsites.hlx.page/past-champions/archive/al-geiberger-1975
> Updated video player

- styles/styles.css
even when it's the first element in the teaser.
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
- After: https://teaser-h2-fontsize--theplayers--hlxsites.hlx.page/volunteer/volunteer-info/
> fix: ensure h2 font size is respected 

- blocks/header/header.js
Test URLs:
- After: https://countdown--theplayers--hlxsites.hlx.page/
> feat: hide countdown after end is reached

- blocks/leaderboard/leaderboard.js
Test URLs:
- After: https://leaderboard--theplayers--hlxsites.hlx.page/
> Leaderboard

- blocks/leaderboard/leaderboard.js
- blocks/news/news.js
2 things going on here:
1: fix the news query to use the upper case our code
2: update leaderboard block to link to the player profile rather than the scorecard
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/drafts/shsteimer/
- Before: https://main--theplayers--hlxsites.hlx.page/news
- After: https://feed-fixes--theplayers--hlxsites.hlx.page/
- After: https://feed-fixes--theplayers--hlxsites.hlx.page/drafts/shsteimer/
- After: https://feed-fixes--theplayers--hlxsites.hlx.page/news
> Feed fixes

- blocks/header/header.css
- blocks/header/header.js
See https://adobe-dx-support.slack.com/archives/C03GXBSC72T/p1676388053809299
Test URLs:
- After: https://header-no-login--theplayers--hlxsites.hlx.page/
> fix: allow user nav/login to be removed from header

- blocks/header/header.css
Test URLs:
Before: https://main--theplayers--hlxsites.hlx.live/
After: https://tstorm-icon--theplayers--hlxsites.hlx.live/
> remove *F from after as that now comes from the api response

- blocks/columns/columns.css
Fix: https://pgatour.atlassian.net/browse/AEMFDEV-21
Test URLs:
- After: https://AEMFDEV-21--Logo-Styling-Off--theplayers--hlxsites.hlx.page/
Changes:
- Updated columns css to style icon's within
> Added styling to logos in column blocks

- blocks/footer/footer.css
- blocks/footer/footer.js
- blocks/header/header.js
- blocks/sponsors/sponsors.css
- blocks/sponsors/sponsors.js
Fix #87 
Test URLs:
- Before: https://main--theplayers--hlxsites.hlx.page/sponsors
- After: https://sponsors-new-structure--theplayers--hlxsites.hlx.page/drafts/shsteimer/sponsors
- After: https://sponsors-new-structure--theplayers--hlxsites.hlx.page/drafts/shsteimer/home
> Sponsors new structure

- tools/sidekick/config.json
Test URLs:
- After: https://sk-conf--theplayers--hlxsites.hlx.page/
> chore: sk conf for host

- blocks/table/table.css
Fix: https://pgatour.atlassian.net/browse/AEMFDEV-62
Test URLs:
Before: https://main--theplayers--hlxsites.hlx.page/
After: https://aemfdev-62--table-icons--theplayers--hlxsites.hlx.page/
Changes: Updated Icon CSS within table blocks
> AEMFDEV-62 Updated Table Icon CSS

- scripts/delayed.js
- scripts/scripts.js
Test URLs:
- After: https://fevo--theplayers--hlxsites.hlx.page/drafts/shsteimer/charity
See https://adobe-dx-support.slack.com/archives/C03GXBSC72T/p1690550356398579
Note, the fevo offer never loads on that test page, not a real offer code yet, and primarily this is for Fedex st. Jude, just doing it here so I can merge it to other tournament sites.
> fevo script injection for buttons

- blocks/news/news.js
https://pgatour.atlassian.net/browse/TDW-2219
Test URLs:
- After: https://TDW-2219-Video-Call--theplayers--hlxsites.hlx.page/
> - Updated Video Call

- blocks/marketing/marketing.js
https://pgatour.atlassian.net/browse/TDW-2152
Test URLs:
- After: https://TDW-2152-Ad-Params--theplayers--hlxsites.hlx.page/
> - Updated ads handling

- blocks/table/table.css
- blocks/table/table.js
https://pgatour.atlassian.net/browse/TDW-2358
Test URLs:
- After: https://TDW-2358-Table-Data--theplayers--hlxsites.hlx.page/
> TDW-2358 Updated Data Table to leverage MW feed

- blocks/table/table.js
https://pgatour.atlassian.net/browse/TDW-2393
Test URLs:
- After: https://tdw-2393-table-params--theplayers--hlxsites.hlx.page/
> TDW-2393 updated table params to fetch current year

- styles/styles.css
Ticket: https://pgatour.atlassian.net/browse/TDW-2390
Test URLs:
- After: https://tdw-2390-adcont-size--theplayers--hlxsites.hlx.page/
> TDW-2390 updated ad container sizing

- blocks/share/share.css
https://pgatour.atlassian.net/browse/TDW-2232
Test URLs:
- After: https://tdw-2232-change-x-color--theplayers--hlxsites.hlx.page/
> TDW-2232 changed x logo colour
